export CHEF_SERVER_SELECTOR_HOME='/Users/yiqing.zhu/tools/chef-server-selector'
alias 'githubc'='git commit --author="sbbird.zhu <sbbird.zhu@gmail.com>"'
alias e='emacsclient -t'
alias ec='emacsclient -c'
alias fn='find . -name'
